In [10]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf

In [11]:
os.getcwd()

'F:\\KARTIK\\2021\\Freezing of Gait'

In [12]:
data_path_1 = os.path.join(os.getcwd(), 'dataset_fog_release', 'dataset', 'features', 'freq_1.csv')
if os.path.exists(data_path_1):
    print(True)

True


In [13]:
data_path_2 = os.path.join(os.getcwd(), 'dataset_fog_release', 'dataset', 'features', 'time_1.csv')
if os.path.exists(data_path_2):
    print(True)

True


In [14]:
#Load the time features
time_features = pd.read_csv(data_path_2)

#Load the frequency features
freq_features = pd.read_csv(data_path_1)

In [15]:
features = [time_features.iloc[:,0:12], freq_features.iloc[:,[0,1,2,9,10,11,36,37,38]]]
final_features = pd.concat(features, axis = 1)

#Get the shape of the dataframe
final_features.shape

(12658, 21)

In [16]:
final_features.head()

0  Minimum_A_F  Maximum_A_F  Median_A_F   Mean_A_F  ArmMean_A_F    RMS_A_F  \
0  0         -121           90       -50.0 -50.875000     0.000000  64.817773   
1  0         -121           40       -50.0 -49.000000     0.000000  60.410833   
2  0          -90           50       -50.0 -48.437500     0.000000  55.761770   
3  0         -161           40       -50.0 -52.390625    34.896197  63.512179   
4  0         -141           20       -60.0 -58.656250    48.458215  64.156060   

   Variance_A_F    STD_A_F  Kurtosis_A_F  ...  TrimMean_A_F    FI_A_F  \
0   1613.078125  40.163144      2.808410  ...    -50.875000  3.033743   
1   1248.468750  35.333677     -0.615322  ...    -49.000000  4.369914   
2    763.183594  27.625778      3.044294  ...    -48.437500  4.654526   
3   1289.019287  35.902915      1.414610  ...    -52.390625  3.609687   
4    675.444336  25.989312      1.215502  ...    -58.656250  0.921765   

     FI_A_V    FI_A_L         P_A_F         P_A_V          P_A_L   ENt_A_F  \
0  0.198547  0.299836  46235.233242  4.192775e+06  426656.746293  2.848596   
1  0.216587  0.171385  39618.105379  4.128661e+06  447118.114826  2.367487   
2  0.207979  0.175159  52733.710047  4.124724e+06  484651.284698  2.113819   
3  0.201192  0.245850  55848.235299  4.081800e+06  524303.997092  2.267055   
4  0.209767  0.238337  24854.924149  4.041311e+06  448136.977828  3.036838   

    ENt_A_V   ENt_A_L  
0  2.773791  2.627315  
1  3.110655  2.808822  
2  3.063275  2.812928  
3  2.900160  2.677376  
4  2.981486  2.809107  

[5 rows x 21 columns]

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.utils import shuffle

In [18]:
X = final_features.iloc[:,1:]
y = final_features.iloc[:,0]

In [19]:
X, y = shuffle(X,y, random_state = 0)

X = normalize(X)

In [20]:
rf = RandomForestClassifier(random_state = 0)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, random_state = 0)

In [22]:
model = rf.fit(X_train, y_train)

In [23]:
y_pred = model.predict(X_test)

In [24]:
accuracy_score(y_test, y_pred)

0.8701421800947867

In [25]:
cnf = confusion_matrix(y_test, y_pred)
print(cnf)

[[2634   68    0]
 [ 284  120    0]
 [  44   15    0]]


In [26]:
# For class pre-FoG
tp = cnf[1][1]
tn = cnf[0][0] + cnf[0][2] + cnf[2][0] + cnf[2][2]
fp = cnf[1][0] + cnf[1][2]
fn = cnf[0][1] + cnf[2][1]

In [27]:
precision = tp/(tp + fp)
recall =  tp / (tp + fn)    #sensitivity
F1_score = (2*tp) / (2*tp + fp + fn)

In [28]:
print("The evaluation metrics are:\nprecision = {},\nrecall = {}, \nF1-score = {}".format(precision, recall, F1_score) )

The evaluation metrics are:
precision = 0.297029702970297,
recall = 0.5911330049261084, 
F1-score = 0.3953871499176277
