In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import normalize
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.utils import shuffle

os.chdir(r"F:\\KARTIK\\2021\\Freezing of Gait")

In [2]:
data_path = os.path.join(os.getcwd(), 'dataset_fog_release', 'dataset', 'FINAL FEATURES', 'final_ftrs_size_1.5_6.csv')
if os.path.exists(data_path):
    print(True)

True


In [3]:
df = pd.read_csv(data_path)
df.head()

Unnamed: 0  0  Minimum_A_F  Maximum_A_F     RMS_A_F   Variance_A_F  \
0        4513  0           40          101   68.897682     146.236084   
1        6459  0          121          161  147.941289      65.795898   
2        5352  0          -60          -30   45.259667      65.405273   
3        1004  0        -1838          252  373.988553   66290.875000   
4        6584  0        -1333         2424  591.102439  330280.389600   

      STD_A_F  Kurtosis_A_F  Skewness_A_F  RangeA_F  ...  RangeA_L  \
0   12.092811      0.132800     -0.243624        61  ...        40   
1    8.111467      0.595423     -0.389017        40  ...        59   
2    8.087353     -0.444150     -0.240541        30  ...        60   
3  257.470144     19.069658     -3.286888      2090  ...      1396   
4  574.700261      5.406269      1.861791      3757  ...      2662   

          P_A_F        P_A_V         P_A_L    EN_A_F    EN_A_V    EN_A_L  \
0  2.183501e+04  4427629.348  9.210375e+04    303801  67607584   1532516   
1  9.363149e+04  4041450.995  4.598698e+05   1400744  61529900   6843157   
2  8.636048e+03  3218410.004  1.361277e+06    131100  49471207  20523664   
3  1.241389e+06  4964803.167  9.774890e+05   8951516  59219551  10638426   
4  1.058125e+07  5077586.836  1.400977e+07  22361734  70991769  28605488   

    ENt_A_F   ENt_A_V   ENt_A_L  
0  2.810514  3.107545  2.969939  
1  3.133801  3.127514  3.224569  
2  3.020430  3.162497  3.075741  
3  2.986659  2.666471  3.162248  
4  2.959794  2.191758  2.224221  

[5 rows x 34 columns]

In [4]:
df['Energy_Mean'] = (df['EN_A_F'] + df['EN_A_V'] + df['EN_A_L'])/3
df = df.drop(['EN_A_F','EN_A_V','EN_A_L','Unnamed: 0'], axis = 1)

In [5]:
df.head()

0  Minimum_A_F  Maximum_A_F     RMS_A_F   Variance_A_F     STD_A_F  \
0  0           40          101   68.897682     146.236084   12.092811   
1  0          121          161  147.941289      65.795898    8.111467   
2  0          -60          -30   45.259667      65.405273    8.087353   
3  0        -1838          252  373.988553   66290.875000  257.470144   
4  0        -1333         2424  591.102439  330280.389600  574.700261   

   Kurtosis_A_F  Skewness_A_F  RangeA_F  Minimum_A_V  ...     STD_A_L  \
0      0.132800     -0.243624        61         1009  ...   10.211389   
1      0.595423     -0.389017        40          960  ...   11.319479   
2     -0.444150     -0.240541        30          862  ...   10.675432   
3     19.069658     -3.286888      2090          598  ...  161.458247   
4      5.406269      1.861791      3757          470  ...  477.212691   

   Kurtosis_A_L  RangeA_L         P_A_F        P_A_V         P_A_L   ENt_A_F  \
0     -0.379448        40  2.183501e+04  4427629.348  9.210375e+04  2.810514   
1     -0.076552        59  9.363149e+04  4041450.995  4.598698e+05  3.133801   
2      1.155050        60  8.636048e+03  3218410.004  1.361277e+06  3.020430   
3     10.060142      1396  1.241389e+06  4964803.167  9.774890e+05  2.986659   
4      3.516137      2662  1.058125e+07  5077586.836  1.400977e+07  2.959794   

    ENt_A_V   ENt_A_L   Energy_Mean  
0  3.107545  2.969939  2.314797e+07  
1  3.127514  3.224569  2.325793e+07  
2  3.162497  3.075741  2.337532e+07  
3  2.666471  3.162248  2.626983e+07  
4  2.191758  2.224221  4.065300e+07  

[5 rows x 31 columns]

In [16]:
# Split the data for the classifier
y = df['0'].values
X = df.iloc[:,1:]
#X = normalize(X)
X, y = shuffle(X, y, random_state = 2)

In [17]:
# Initiate the 10 - fold split 
kf = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 2)

# Initiate a decision tree model
clf = DecisionTreeClassifier(class_weight=None, 
                            criterion='entropy',
                            max_depth=10,
                            max_features=3, 
                            max_leaf_nodes=None,
                            min_impurity_decrease=0.0, 
                            min_samples_leaf=18, 
                            min_samples_split=10,
                            min_weight_fraction_leaf=0.0, 
                            #presort=False,
                            random_state=2, 
                            splitter='best'
                            )
# split()  method generate indices to split data into training and test set.
for (train_index, test_index), i in zip(kf.split(X, y), range(10)):
    print(f'Fold:{i}, Train set: {len(train_index)}, Test set:{len(test_index)}')

Fold:0, Train set: 1988, Test set:221
Fold:1, Train set: 1988, Test set:221
Fold:2, Train set: 1988, Test set:221
Fold:3, Train set: 1988, Test set:221
Fold:4, Train set: 1988, Test set:221
Fold:5, Train set: 1988, Test set:221
Fold:6, Train set: 1988, Test set:221
Fold:7, Train set: 1988, Test set:221
Fold:8, Train set: 1988, Test set:221
Fold:9, Train set: 1989, Test set:220


In [18]:
score = cross_val_score(clf, X, y, cv= kf, scoring="accuracy")
print(f'Scores for each fold are: {score}')
print(f'Average score: {"{:.2f}".format(score.mean())}')

Scores for each fold are: [0.79638009 0.80090498 0.74208145 0.77375566 0.77828054 0.76923077
 0.77375566 0.77375566 0.7918552  0.81818182]
Average score: 0.78


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2, stratify = y, test_size = 0.40)

In [20]:
m = clf.fit(X_train, y_train)
y_pred = m.predict(X_test)
accuracy_score(y_test, y_pred)

0.7748868778280543

In [21]:
cnf = confusion_matrix(y_test, y_pred)
print(cnf)

[[ 68  70   4]
 [ 28 612   7]
 [  3  87   5]]


In [22]:
# For class pre-FoG
tp = cnf[1][1]
tn = cnf[0][0] + cnf[0][2] + cnf[2][0] + cnf[2][2]
fp = cnf[1][0] + cnf[1][2]
fn = cnf[0][1] + cnf[2][1]

In [23]:
precision = tp/(tp + fp)
recall =  tp / (tp + fn)    #sensitivity
F1_score = (2*tp) / (2*tp + fp + fn)

In [24]:
print("The evaluation metrics are:\nprecision = {},\nrecall = {}, \nF1-score = {}".format(precision, recall, F1_score) )

The evaluation metrics are:
precision = 0.9459041731066461,
recall = 0.7958387516254877, 
F1-score = 0.864406779661017
